{
 "title": "Логи конвейера",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "contour",
    "label": "Contour",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "GENERIC CONVEYOR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{nodename=~\"management-server.*\", unit=\"conveyor_generic.service\", contour=\"$contour\"} |= ``"
    }
   ]
  },
  {
   "title": "PK1 CONVEYOR",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{nodename=~\"management-server.*\", unit=\"conveyor_pk1.service\", contour=\"$contour\"} |= ``"
    },
    {}
   ]
  },
  {
   "title": "PK2 CONVEYOR",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{nodename=~\"management-server.*\", unit=\"conveyor_pk2.service\", contour=\"$contour\"} |= ``"
    }
   ]
  }
 ]
}