{
 "title": "PostgreSQL DB Dashboard",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds)"
   },
   {
    "name": "release",
    "label": "Release",
    "query": "query_result(pg_exporter_last_scrape_duration_seconds{kubernetes_namespace=\"$namespace\"})"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "query_result(pg_up{release=\"$release\", contour=\"$contour\"})"
    }
   },
   { "name": "datname", "label": "Database", "query": "label_values(datname)" },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   },
   { "name": "contour", "label": "Contour", "query": { "query": "label_values(contour)" } }
  ]
 },
 "panels": [
  {
   "title": "General Counters, CPU, Memory and File Descriptor Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "start time of the process",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{release=\"$release\", instance=\"$instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Current fetch data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current insert data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_inserted{release=\"$release\", datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Current update data",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{release=\"$release\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{release=\"$release\", instance=\"$instance\"}[5m]) * 1000)",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{release=\"$release\", instance=\"$instance\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{release=\"$release\", instance=\"$instance\"}",
     "legendFormat": "Open FD"
    }
   ]
  },
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_random_page_cost{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_seq_page_cost{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=\"active\"} !=0",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Update data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Fetch data (SELECT)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Insert data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_inserted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Lock tables",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_locks_count{datname=~\"$datname\", instance=~\"$instance\", mode=~\"$mode\"} != 0",
       "legendFormat": "{{datname}},{{mode}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Idle sessions",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=~\"$datname\", instance=~\"$instance\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}",
       "legendFormat": "{{datname}}, s: {{state}}"
      }
     ]
    },
    {
     "title": "Delete data",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{datname=~\"$datname\", instance=~\"$instance\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=~\"$datname\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=~\"$datname\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{instance=\"$instance\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean_total{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "timeseries",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time_total{instance=\"$instance\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time_total{instance=\"$instance\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    }
   ]
  },
  { "title": "KRTMRD Database Custom Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cтарейшая транзакция",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_oldest_transaction{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Старейший запрос",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_oldest_query{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Старейшая сессия",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_oldest_session{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во сеансов",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_active_sessions_total{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во дедлоков",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_deadlocks{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сеансы по адресам",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_sessions_by_client_address{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сеансы по пользователям",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_sessions_by_client_name{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во транзакций",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_transactions_total{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Проблемы с сеансами",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_session_issues{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активность",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_session_activity{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статусы сеансов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_session_statuses{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Состояния ожидания",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_session_waiting_states{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ожидания",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_wait_metrics{contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}