{
 "title": "Состояние микросервисов комплекса",
 "description": "initial",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(systemd_unit_info,job)"
    }
   },
   { "name": "contour", "label": "Contour", "query": { "query": "label_values(contour)" } }
  ]
 },
 "panels": [
  {
   "title": "Рабочее место оператора \"Приёмный Комплекс 1\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Рабочее место оператора \"Приёмный Комплекс 1\"",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"$job\", instance=~\"rmo-pk1.*\", state=\"active\", name=\"rmo-pk1.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Management Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "0 Запускатель конвейера - guidance-conveyor",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=\"guidance-conveyor.service\", instance=~\"management-server.*\", state=\"active\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "17 Управление ВЧ-коммутатором - rf-commutator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=\"rf-commutator.service\", instance=~\"management-server.*\", state=\"active\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "6 Запускатель и контроль - TasksStarterProcessor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=\"TasksStarterProcessor.service\", instance=~\"management-server.*\", state=\"active\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "7 Управление сопровождением - guidanceControl",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=\"guidanceControl.service\", instance=~\"management-server.*\", state=\"active\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Сервер УПНКИ-01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "16 Управление УПНКИ-01 - upnki_01_controller",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-01.*\", state=\"active\", name=\"upnki_01_controller.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 13 Захват сигнала с АЦП - ac_receiver",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-01.*\", state=\"active\", name=\"ac_receiver.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "11 Формирование блоков спектра - fft",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-01.*\", state=\"active\", name=\"fft.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "18 Управление оценкой параметров сигналов - signalEstimation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-01.*\", state=\"active\", name=\"signalEstimation.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 19. Расчет параметров оцениваемого сигнала- signalsNKICalculation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-01.*\", state=\"active\", name=\"signalsNKICalculation.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "14 Запись ДДЗ - ddz_recorder",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-01.*\", state=\"active\", name=\"ddz_recorder.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Сервер УПНКИ-02", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": " 13 Захват сигнала с АЦП - ac_receiver_L",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"ac_receiver_L.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 13 Захват сигнала с АЦП - ac_receiver_S",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"ac_receiver_S.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 13 Захват сигнала с АЦП - ac_receiver_X",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"ac_receiver_X.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 11 Формирование блоков спектра - fft_L",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"fft_L.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 11 Формирование блоков спектра - fft_S",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"fft_S.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 11 Формирование блоков спектра - fft_X",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"fft_X.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "12 Выделение сигналов в спектре - spectrumSignalDetection_L",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"spectrumSignalDetection_L.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "12 Выделение сигналов в спектре - spectrumSignalDetection_S",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"spectrumSignalDetection_S.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "12 Выделение сигналов в спектре - spectrumSignalDetection_X",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"spectrumSignalDetection_X.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 14 Запись ДДЗ - ddz_recorder_L",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"ddz_recorder_L.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 14 Запись ДДЗ - ddz_recorder_S",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"ddz_recorder_S.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 14 Запись ДДЗ - ddz_recorder_X",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"ddz_recorder_X.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "15 Управление обнаружением сигналов - bandSignalsDetection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", instance=~\"upnki-02.*\", state=\"active\", name=\"bandSignalsDetection.service\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Сервер БСН-01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "2 ЦУ задачи - TrajectoryPrediction",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=~\"TrajectoryPrediction.service\", state=\"active\", instance=~\"bsn1.*\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "8 Формирование ЦУ сопровождения - Deviations receiver",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=\"DR.service\", state=\"active\", instance=~\"bsn1.*\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "9 Имитатор РПУ сопровождения - emuSDR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=\"emuSDR.service\", state=\"active\", instance=~\"bsn1.*\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "4 Имитатор ОПУ - emitatorOPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=\"emitatorOPU.service\", state=\"active\", instance=~\"bsn1.*\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 3 Управление ОПУ - OPY_Control",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "systemd_unit_state{job=\"systemd_exporter\", name=\"OPY_Control.service\", state=\"active\", instance=~\"bsn1.*\", contour=\"$contour\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}